Rem FOR %%A IN (clovers/*.svg) DO "C:\Program Files\Inkscape\bin\inkscape.exe" clovers/%%A --export-type="png"
Rem FOR %%A IN (spades/*.svg) DO "C:\Program Files\Inkscape\bin\inkscape.exe" spades/%%A --export-type="png"
Rem FOR %%A IN (diamonds/*.svg) DO "C:\Program Files\Inkscape\bin\inkscape.exe" diamonds/%%A --export-type="png"
Rem FOR %%A IN (heart/*.svg) DO "C:\Program Files\Inkscape\bin\inkscape.exe" heart/%%A --export-type="png"
Rem FOR %%A IN (baksida/*.svg) DO "C:\Program Files\Inkscape\bin\inkscape.exe" baksida/%%A --export-type="png"
FOR %%A IN (knakers/*.svg) DO "C:\Program Files\Inkscape\bin\inkscape.exe" knakers/%%A --export-type="png"